### PR TITLE
Update spanish translation

### PR DESCRIPTION
**Pull request by xphnx**

### CODE REVIEW

**Comment by rfc2822** [comment]
Cool, thanks!

**Comment by devvv4ever** [comment]
Hi xphnx,

thanks again for making a translation for DAVdroid into your language!

We're trying to make a group for all translators in our new [forums](https://davdroid.bitfire.at/forums). Is it possible for you to join there? It would be really great, so that we can better manage the growing translations base.

Thank you!

**Comment by xphnx** [comment]
El 2015-09-06 13:37, devvv4ever escribió:
> Hi xphnx,
> 
> thanks again for making a translation for DAVdroid into your language!
> 
> We're trying to make a group for all translators in our new
> [forums](https://davdroid.bitfire.at/forums). Is it possible for you
> to join there? It would be really great, so that we can better manage
> the growing translations base.
> 
> Thank you!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bitfireAT/davdroid/pull/471#issuecomment-138073675


OK I have registered into your forums. same nick. Regards.

**Comment by devvv4ever** [comment]
You can have you previous posts from github linked to your new email address if you want!

**Pull request merged**
