### PR TITLE
Added dutch translation file

### PR DESCRIPTION
**Pull request by dehart**
Not sure if this file is enough for the Dutch translation let me know if you need more.

### CODE REVIEW

**Comment by rfc2822** [comment]
Hey, thanks ☺

**Comment by devvv4ever** [comment]
Hello dehart,

thanks again for making a translation for DAVdroid into your language!

We're trying to make a group for all translators in our new [forums](https://davdroid.bitfire.at/forums). Is it possible for you to join there? It would be really great, so that we can better manage the growing translations base.

Thank you!

**Comment by dehart** [comment]
Hi,

I've joined to forums, let me know when you need something translated.
Username = Michael

Op zo 6 sep. 2015 om 13:36 schreef devvv4ever <notifications@github.com>:

**Comment by devvv4ever** [comment]
Thanks, if you want to use your auto-imported Github account (with all the postings associated to you) please write us an email to play@bitfire.at - the you can continue using the old account instead of the newly created one.

**Pull request merged**
